global using Auctria.EcommerceStore.Core.Application.Products;
global using Auctria.EcommerceStore.Core.Application.Products.Commands.CreateProduct;
global using Auctria.EcommerceStore.Core.Application.Products.Commands.DeleteProduct;
global using Auctria.EcommerceStore.Core.Application.Products.Commands.UpdateProduct;
global using Auctria.EcommerceStore.Core.Application.Products.Queries;
global using Auctria.EcommerceStore.Core.Application.Products.Queries.GetProduct;
global using Auctria.EcommerceStore.Core.Application.Products.Queries.ListProducts;
global using Auctria.EcommerceStore.Infrastructure.Persistence.Context;
global using Auctria.EcommerceStore.Web.API.Middleware;